In [2]:
import pandas as pd
import os
os.chdir('/Users/fulinq/Documents/KMITL/FinancialEngineering/Y5/STOCHASTIC OPTIMIZATION/Project/MPT')

In [7]:
price_df = pd.read_excel('28AUG.xlsx', index_col=0)
price_df = price_df.sort_index()
price_df = price_df.ffill()
price_df = price_df.sort_index(ascending=False)
price_df

,KKP MP,KKP DIVIDEND,KKP CorePath Balanced,KKP ACT FIXED,KKP SM CAP,KKP CorePath Extra,KKP SEMICON-H,KKP INCOME-H,KKP S-PLUS,KKP EMXCN-UH,KKP INDIA-H,KKP CASH,KKP EWUS500-UH,KKP VIETNAM,KKP EUROPE-UH
Date,,,,,,,,,,,,,,,
2026-08-28,12.9752,14.2669,18.2555,12.4779,15.0587,13.2384,29.4543,10.4944,10.9207,16.4845,8.2180,10.2718,11.3120,9.7467,11.1543
2026-08-27,12.9747,14.2528,18.2555,12.4812,15.1647,13.2384,29.4543,10.4944,10.9205,16.4845,8.2180,10.2714,11.3120,9.7385,11.1543
2026-08-26,12.9746,14.3069,18.2555,12.4825,15.1502,13.2384,28.8982,10.5071,10.9198,16.3059,8.2180,10.2711,11.3200,9.6610,11.1543
2026-08-25,12.9744,14.1797,18.2479,12.4792,14.9919,13.2339,28.8266,10.4904,10.9191,16.3198,8.1930,10.2710,11.3000,9.5356,11.1038
2026-08-24,12.9741,14.2141,18.1946,12.4762,14.9921,13.1809,28.3946,10.4677,10.9195,15.9639,8.1277,10.2712,11.2884,9.5738,11.0627
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2008-09-16,10.0062,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-09-15,10.0053,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-09-12,10.0024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-09-11,10.0016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-09-10,10.0007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
import numpy as np

log_return_df = np.log(price_df / price_df.shift(-1))*np.sqrt(252)
log_return_df = log_return_df.dropna(how='all')
log_return_df

,KKP MP,KKP DIVIDEND,KKP CorePath Balanced,KKP ACT FIXED,KKP SM CAP,KKP CorePath Extra,KKP SEMICON-H,KKP INCOME-H,KKP S-PLUS,KKP EMXCN-UH,KKP INDIA-H,KKP CASH,KKP EWUS500-UH,KKP VIETNAM,KKP EUROPE-UH
Date,,,,,,,,,,,,,,,
2026-08-28,0.000612,0.015697,0.000000,-0.004198,-0.111351,0.000000,0.000000,0.000000,0.000291,0.000000,0.000000,0.000618,0.000000,0.013361,0.000000
2026-08-27,0.000122,-0.060142,0.000000,-0.001653,0.015186,0.000000,0.302578,-0.019199,0.001018,0.172930,0.000000,0.000464,-0.011223,0.126836,0.000000
2026-08-26,0.000245,0.141768,0.006610,0.004197,0.166741,0.005397,0.039380,0.025251,0.001018,-0.013526,0.048365,0.000155,0.028072,0.207400,0.072033
2026-08-25,0.000367,-0.038465,0.046435,0.003817,-0.000212,0.063703,0.239698,0.034388,-0.000582,0.350020,0.127030,-0.000309,0.016304,-0.063467,0.058867
2026-08-24,0.000734,-0.084985,-0.025369,-0.002163,-0.105850,-0.029960,-0.426980,-0.013491,-0.000145,-0.224825,-0.067241,0.000309,0.028432,-0.010940,-0.051002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2008-09-17,0.001269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-09-16,0.001428,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-09-15,0.004602,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-09-12,0.001270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-09-11,0.001429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
log_return_df.describe()

,KKP MP,KKP DIVIDEND,KKP CorePath Balanced,KKP ACT FIXED,KKP SM CAP,KKP CorePath Extra,KKP SEMICON-H,KKP INCOME-H,KKP S-PLUS,KKP EMXCN-UH,KKP INDIA-H,KKP CASH,KKP EWUS500-UH,KKP VIETNAM,KKP EUROPE-UH
count,4308.000000,3452.000000,2850.000000,2645.000000,2373.000000,1806.000000,1245.000000,1116.000000,1049.000000,614.000000,524.000000,424.000000,415.000000,259.000000,138.000000
mean,0.000959,0.001635,0.002284,0.001329,0.002739,0.002474,0.013834,0.000687,0.001333,0.012890,-0.005938,0.001006,0.004801,-0.001589,0.012503
std,0.001074,0.160720,0.073087,0.007066,0.175196,0.115080,0.376709,0.061991,0.001992,0.217521,0.161839,0.000926,0.166861,0.198468,0.130611
min,-0.001948,-1.920908,-0.818937,-0.072857,-1.874710,-1.202744,-1.739059,-0.303403,-0.010474,-1.276913,-0.734814,-0.001553,-0.939594,-0.911747,-0.338249
25%,0.000392,-0.072648,-0.028960,-0.001471,-0.091858,-0.044789,-0.183416,-0.027927,0.000311,-0.083347,-0.084019,0.000464,-0.076900,-0.103123,-0.064141
50%,0.000680,0.007188,0.001998,0.001369,0.007668,0.000629,0.005792,0.000000,0.001337,0.007237,0.000000,0.000781,0.008302,0.000000,0.000000
75%,0.001217,0.088322,0.037757,0.004176,0.102191,0.057654,0.228119,0.030592,0.002352,0.117275,0.068507,0.001268,0.096899,0.097791,0.087432
max,0.035867,1.344023,0.520138,0.056246,1.064627,0.721104,2.657532,0.317585,0.016378,0.947597,1.356439,0.005037,1.111151,0.906300,0.435890